---
- name: Creating Kubernetest Service
  hosts: Kubernetes
  become: true

  tasks:
   - name: Creat Service
     command: kubectl apply -f Project-Service.yml
     args:
      chdir: "/opt/Kubernetes" 
