apiVersion: apps/v1
kind: Deployment
metadata:
  name: jannat-deployment
spec:
  selector:
    matchLabels:
      app: jannat-devops-project
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1

  template:
    metadata:
      labels:
        app: jannat-devops-project
    spec:
      containers:
      - name: jannat-devops-project
        image: jannatbawa/myrepo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 
