apiVersion: v1
kind: Service
metadata: 
  name: jannat-service
  labels:
    app: jannat-devops-project
spec:
  selector:
      app: jannat-devops-project
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
      protocol: TCP
